name: Build and Release Rust Binary

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'Cargo.toml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build Release Binary
        run: cargo build --release

      - name: Publish Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest Release
          files: target/release/cf-gateway-sync
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
